#!/bin/sh
# Bake the current pywal palette into theme.css (and the dark theme-color meta tag).
# Run after changing wallpaper, then commit. The phone gets whatever is committed.
set -e
cd "$(dirname "$0")"
WAL="${WAL_COLORS:-$HOME/.cache/wal/colors.json}"
python3 - "$WAL" <<'PY'
import json, re, sys, os
d = json.load(open(sys.argv[1]))
c, sp = d['colors'], d['special']
hx = lambda s: ','.join(str(int(s[i:i+2], 16)) for i in (1, 3, 5))
accent, bg, fg = c['color1'], sp['background'], sp['foreground']
css = f"""/* Generated by wal-theme.sh from {os.path.basename(d.get('wallpaper', '?'))}. Do not edit; rerun the script. */
:root {{
  --accent: {accent};
  --accent-rgb: {hx(accent)};
  --wal-bg: {bg};
  --wal-bg-rgb: {hx(bg)};
  --wal-fg: {fg};
}}
"""
open('theme.css', 'w').write(css)
html = open('index.html').read()
html, n = re.subn(r'(<meta name="theme-color" media="\(prefers-color-scheme: dark\)" content=")#[0-9a-fA-F]{6}(")', r'\g<1>' + bg + r'\2', html)
open('index.html', 'w').write(html)
print(f"theme.css: accent {accent}, dark bg {bg}, fg {fg}; theme-color meta {'updated' if n else 'NOT FOUND'}")
PY
